# Tarea 1 version 2

### Gustavo Pinto

## 3. Calibración y simulaciones


A continuacion presentamos el sistema a resolver:

$$
P_j^{1-\epsilon_Q}=Z_j^{\epsilon_Q-1}\left(a_j+\left(1-a_j\right)\left(P_j^M\right)^{1-\epsilon_Q}\right)
$$

Donde $P_j^M$ es:

$$P_j^M=(\sum_{i=1}^{N+1} \omega_{ji}((1+\chi_{ji})P_i)^{1-\epsilon_M})^{\frac{1}{1-\epsilon_M}}$$

Sustituimos y obtenemos la expresion para precios:

$$
P_j^{1-\epsilon_Q}=Z_j^{\epsilon_Q-1}a_j+Z_j^{\epsilon_Q-1}(1-a_j)(\sum_{i=1}^{N+1} \omega_{ji}((1+\chi_{ji})P_i)^{1-\epsilon_M})
$$

Que matricialmente puede ser escrito como:

$$
P^{1-\epsilon_Q}=a \circ Z^{\epsilon_Q-1}+((1-a) \circ Z^{\epsilon_Q-1}) \circ [(\Omega\circ (1+\chi)^{1-\epsilon_Q})(P^\prime)^{1-\epsilon_Q}]
$$

Una expresion para el consumo es:

$$P_jC_j=\beta_jP_CC $$

donde $P_CC$ es la canasta de consumo.

Por lo tanto, podemos despejar el consumo y tener:

$$C_j=\frac{\beta_jP_CC}{P_j} $$


Una vez los precios y consumo listos, ahora podemos resolver para cantidades $Q$. Para esto tenemos lo siguiente:

$$Q_j=C_j+C_j^*+\sum_{i=1}^{N+1} M_{i j}$$
$$M_j=((1-a_j) \frac{P_j}{P_j^M})^{\epsilon_Q} Z_j^{\epsilon_Q-1} Q_j$$
$$M_{j i}=((1+\chi_{j i}) \frac{P_i}{P_j^M})^{\epsilon_Q} M_j \omega_{j i}$$

Introducimos la segunda ecuacion en la primera y obtenemos:

$$M_{j i}=((1+\chi_{j i}) {P_i})^{-\epsilon_Q} ((1-a_j) {P_j})^{\epsilon_Q} Z_j^{\epsilon_Q-1} Q_j \omega_{j i}$$

Ahora, podemos introducir esta expresion en la primera y asi tenemos:

$$Q_j=C_j+C_j^*+((1-a_j) {P_j})^{\epsilon_Q}Z_j^{\epsilon_Q-1} Q_j\sum_{i=1}^{N+1} ((1+\chi_{j i}) {P_i})^{-\epsilon_Q}   \omega_{j i}$$

Expresado en forma matricial queda:

$$Q=C+C^*+((1-a) \circ {P})^{\epsilon_Q} \circ Z^{\epsilon_Q-1} \circ Q [ ((1+\chi)^{-\epsilon_Q}\circ \Omega) ({P}^\prime)^{-\epsilon_Q}$$

Solo falta resolver de forma endogena el consumo que depende las ventas. Para ello tenemos la siguiente expresion:

$$
1+\Pi+R \bar{K}-\bar{Y}=\frac{1}{\sum_{j=1}^{N+1} a_j Z_j^{\epsilon_Q-1} P_j^{\epsilon_Q-1} s_j}
$$

donde $s_j= \frac{P_jQ_j}{P_CC}$ . Sabiendo que:

$$C_j= \frac{\beta_j(1+\Pi+R \bar{K}-\bar{Y})}{P_j} $$

Podemos escribir $C_j$ como:

$$C_j= \frac{\beta_j}{P_j\sum_{j=1}^{N+1} a_j Z_j^{\epsilon_Q-1} P_j^{\epsilon_Q-1} s_j} $$

Cuya forma matricial es:

$$C_j= \beta (a \circ Z^{\epsilon_Q-1} \circ (P^{\epsilon_Q} s))^{-1}$$

donde $P^{1-\epsilon_Q}$ es el vector:

$$P_{j}^{1-\epsilon_Q}=\begin{bmatrix}
P_{1}^{1-\epsilon_Q} \\
P_{2}^{1-\epsilon_Q}\\
\vdots  \\
P_{N}^{{1-\epsilon_Q}}
\end{bmatrix}$$

el vector $a$ es:

$$a_{j}=\begin{bmatrix}
a_{1} \\
a_{2}\\
\vdots  \\
a_{N}
\end{bmatrix}$$

el vector $z$ es:

$$z_{j}^{1-\epsilon_Q}=\begin{bmatrix}
z_{1}^{1-\epsilon_Q} \\
z_{2}^{1-\epsilon_Q}\\
\vdots  \\
z_{N}^{{1-\epsilon_Q}}
\end{bmatrix}$$

Y la matriz $\Omega$ es:

$$\begin{bmatrix}
\omega_{11} & \cdots & \omega_{1N} \\
\vdots & \ddots & \vdots  \\
\omega_{N1} & \cdots &\omega_{NN}
\end{bmatrix}$$

donde el vector $C$ se ve:

$$C_{j}=\begin{bmatrix}
C_{1} \\
C_{2}\\
\vdots  \\
C_{N+1}
\end{bmatrix}$$

donde el vector $s$ se ve:

$$s_{j}=\begin{bmatrix}
s_{1} \\
s_{2}\\
\vdots  \\
s_{N+1}
\end{bmatrix}$$

donde el vector $\beta$ se ve:

$$\beta_{j}=\begin{bmatrix}
\beta_{1} \\
\beta_{2}\\
\vdots  \\
\beta_{N+1}
\end{bmatrix}$$

donde el vector $C^*$ se ve:

$$C^*_{j}=\begin{bmatrix}
C^*_{1} \\
C^*_{2}\\
\vdots  \\
C^*_{N+1}
\end{bmatrix}$$

Y la matriz distorsiones $1+\chi$ es:

$$\begin{bmatrix}
1 & \cdots & 1 \\
\vdots & \ddots & \vdots  \\
1 & \cdots &1
\end{bmatrix} +\begin{bmatrix}
\omega_{11} & \cdots & \omega_{1N} \\
\vdots & \ddots & \vdots  \\
    \omega_{N1} & \cdots &\omega_{NN}
\end{bmatrix}$$


## 3.1

- En primer lugar vamos a calibrar la matriz $\Omega$ compuesta de los elementos $\omega_{ji}$. Para ello, se utilizara la base de datos de la BEA que provee la matriz de insumos productos de la economia estadounidense en 1997. Especificamente prestaremos atencion a la fila "Total Intermediate". La definicion vista en clases de $\omega{ji}$ es de la importancia que tiene una industria $j$ proveyendo insumos a otra industria $i$ o mejor dicho la production network. A partir de esta idea, calcularemos los elementos de la matriz $\Omega$ como:

$$\Omega=\omega_{ji}= \frac{P_iM_{ji}}{Total Intermediate_j}$$

- A continuacion calibraremos el vector $\beta_j$. Este parametro se entiende como la importancia o valoracion subjetiva que tienen los hogares por bienes. Es decir, la ponderacion que se le va a dar a cada bien dentro de la canasta de consumo. Para calibrar dicho vector, de nuevo utilizaremos la matriz de insumos productos de la BEA. En especial, prestaremos atencion a la siguiente fila: "Personal consumption expenditures". Esta fila reporta el consumo de los privados por los bienes producidos por cada sector. El vector $\beta_j$ se calcula como como:

$$\beta_j= \frac{P_jC_j}{P_cC} $$

- Ahora es el turno de calibrar el vector $a_j$. Esta mide la importancia relativa de los factores productivos a la hora de producir en una firma.Este puede ser encontrado a traves de las condiciones de primer orden de las firmas:

$$W_j=P_ja_j^{1/\epsilon_Q}z_j^{\frac{\epsilon_Q-1}{\epsilon_Q}}(\frac{Q_j}{L_j})^{1/\epsilon_Q}$$

Podemos despejar de esta expresion $a_j$:

$$a_j=\frac{W_j^{\epsilon_Q}L_j}{P_j^{\epsilon_Q}Q_j}$$ 

A partir de aca tenemos que hacer una suposicion importante:

$$\epsilon_Q=1$$

Mas abajo explicaremos esta calibracion. Por lo tanto, la expresion nos queda a:

$$a_j=\frac{W_jL_j}{P_jQ_j}$$ 

Esta informacion puede ser conseguida facilmente con la BEA. Tenemos que prestar atencion a la base de datos, en especial, las columnas "Total industry output (basic prices)" y "Compensation of employees" Donde cada columna nos da los elementos necesarios para construir el vector $a_j$

- Es turno de hablar sobre la elasticidades de sustitucion $\epsilon_Q$ y $\epsilon_M$. En primer lugar se va a seguir manteniendo el supuesto de $\epsilon_Q = \epsilon_M$. Por lo tanto, en el modelo se hara referecia siempre a $\epsilon_Q$. De acuerdo a las estimaciones hechas por Miranda-Pinto, $\epsilon_Q= 2.52$ (Miranda-Pinto, 2021)


- Se va a trabajar en torno al estado estacionario, por lo tanto el vector $z$ sera un vector de unos.

- Tambien necesitamos calibrar las ventas o sales para poder resolver el consumo. Sin embargo, este supone un problema por lo siguiente. $s_j$ se puede calcular como:

$$s_j= \frac{P_jQ_j}{P_cC} $$

Mientras que $P_cC$ se calcula como:

$$ P_cC= \frac{P_jC_j}{\beta_j}$$

Si sustituimos nos quedaria algo como:

$$ s_j= \frac{\beta_jQ_j}{C_j} $$ 

Esto supone un problema ya que vuelve el sistema lineal a algo no lineal. Por lo tanto, se va a calcular con la BEA utilizando la fila "Personal consumption expenditures" y "Total industry output (basic prices)". Asi $s_j$ que es endogeno lo volvemos algo exogeno. El problema es que ante un shock cualquiera, esta variable no se ajustara. La interpretacion de este fenomeno se puede enteder como: ante un shock cualquiera, por ejemplo precios, la canasta de consumo se mantendra fija, es decir los individuos compraran el valor de la canasta siempre, ahora la composicion de esta si cambiara. 

- Por ultimo, solo queda calibrar el vector $C_j^*$. Este se entiende como las exportaciones. En esta economia, el sector $N+1$ es el unico que exporta commodities. Por lo tanto podemos expresar el vector de la siguiente forma:

$$C^*_{j}=\begin{bmatrix}
0 \\
0\\
\vdots  \\
C^*_{N+1}
\end{bmatrix}$$

#### NOTA IMPORTANTE:

El vector $P^{1-\epsilon_Q}$ es de $Nx1$. Tenemos que agregar una ultima fila $P_{N+1}$ cuya funcion sera ver el precio del commoditie que se exporta. El sector escogido para ser el exportador de commodities sera Mining. La posicion de Mining en las matrices de la BEA no necesariamente es la ultima, en realidad es la 2 industria que aparece. Por lo tanto cuando se hable del sector exportador $N+1$ en realidad se hablara del segundo elemento de la matriz/vector. Se trabajara con el vector precios $P^{1-\epsilon_Q}$ de tamaño $N+1xN+1$ con esta consideracion.

Por ultimo, se tomo la decision de sacar ciertos sectores de las simulaciones. El problema es que estos sectores aparecen en la BEA con 0 consumo. Debido a las caracteristicas de nuestra modelo y el hecho de que justamente esas empresas no son las que exportaran, se decidio sacarlas. Los sectores fuera son: Construction y Wholesale Trade. Por lo tanto, quedan 13 sectores, de los cuales, mining es el sector exportador de commodities.

Los principales compradores del sector Mining de acuerdo a la matriz de Leontief son:

| Commodities/Industries                               |   Mining |
|:-----------------------------------------------------|---------:|
| Mining                                               | 1.08969  |
| Manufacturing                                        | 0.870326 |
| Utilities                                            | 0.18927  |
| Government                                           | 0.103382 |
| Finance, insurance, real estate, rental, and leasing | 0.038598 |

Los principales vendedores al sector Mining de acuerdo a la matriz de Leontief son:

| Commodities/Industries                               |     Mining |
|:-----------------------------------------------------|-----------:|
| Mining                                               | 1.08969    |
| Utilities                                            | 0.0133406  |
| Finance, insurance, real estate, rental, and leasing | 0.0118063  |
| Professional and business services                   | 0.00912485 |
| Manufacturing                                        | 0.00665345 |

## 3.2

Ver Anexo para ver resultados

## 3.3

Vemos que cuando se duplica el precio  del bien domestico, el consumo aumenta para todos los bienes menos del que se duplico el precio (se mantiene igual). La produccion cae para todos los sectores pero considerablemente muy poco. En terminos agregados, los ingresos de los hogares aumentan, tambien aumenta el GDP y el consumo agregado.

## 3.4

Ahora se resolvera el modelo con distorsiones downstream. En este caso, cuando el precio del sector commodity se duplica, vemos que el consumo aumenta (no muy considerablemente), la produccion decae tambien muy poco. En terminos agregados, los ingresos del hogar crecen, pero apenas una fraccion muy pequeña (7 veces menos que el caso sin distorsiones). El GDP sube casi 6 veces menos que el caso sin distorsiones. El consumo agregado sube pero igual menos que el caso sin distorsiones.

Si se permiten distorsiones upstream, tenemos los siguientes efectos al duplicar el precio del sector commodity: El consumo sube, la produccion cae ambos de forma no tan fuerte. El ingreso del hogar sube pero apenas 1/3 aproximadamente del caso sin distorsiones. El GDP tambien sube, pero este solo sube tambien un 1/3 aproximadamente de lo que sube en el caso sin distorsiones. El consumo agregado sube, pero este apenas es la mitad de lo que hubiera subido en el caso sin distorsiones.

A continuacion, vamos a comparar los efectos de un shock con distorsiones upstream con uno downstream. Al duplicar los precios, vemos que en el caso downstream este sube menos que el upstream. El consumo domestico de todos los sectores aumenta mas cuando hay un shock en esta economia upstream. La produccion cae menos cuando hay un shock en una economia upstream. En terminos agregados, los ingresos nominales aumentan mas cuando hay un shock con distorsiones upstream que downstream. El GDP, al igual aumenta en el caso del upstream. EL consumo agregado sube mas tambien.

La explicacion de esto puede darse debido a que el sector mining es un sector que predominantemente es mas proveedor que comprador. Por lo tanto, cuando tiene algun tipo de distorsion con sus compradores, esto le afecta mas a la economia que en el caso cuando tiene distorsiones con sus proveedores el sector mining.

Para mayor detalle, consultar el Anexo

## Bibliografia

- Miranda-Pinto, Jorge, and Eric R. Young. 2022. "Flexibility and Frictions in Multisector Models." American Economic Journal: Macroeconomics, 14 (3): 450-80.
- Jorge Miranda Pinto, 2021. "Production Network Structure, Service Share, and Aggregate Volatility," Review of Economic Dynamics, Elsevier for the Society for Economic Dynamics, vol. 39, pages 146-173, January. <https://ideas.repec.org/a/red/issued/19-157.html>


## Anexo Computacional

In [1]:
import pandas as pd
pd.options.mode.chained_assignment = None
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import sympy as sy
%matplotlib inline
import seaborn as sns

df_GDP= pd.read_excel("GDPC1.xls") #Importing Real GDP
df_BDS= pd.read_excel("Datamacro.xlsx", sheet_name=1) #Importing Business Dynamics Statistics (BDS)
df_BEA= pd.read_excel("Table.xlsx", header=4) #Importing Bureau of Economic Analysis (BEA)

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")


## Pregunta 3
### 3.1

In [2]:
#Cleaning and filtering the data from BEA


df_BEA.drop(df_BEA.columns[0], axis=1)
df_BEA.columns = df_BEA.iloc[1]
df_BEA.drop(1, inplace=True)
df_BEA.drop(df_BEA.columns[0],axis=1,inplace=True)
df_BEA.rename(columns={"Name":"Commodities/Industries"}, inplace=True)
df_BEA.drop(0, inplace=True)
df_BEA.set_index("Commodities/Industries", inplace=True)
df_BEA=df_BEA.replace("---", 0)
df_BEA=df_BEA.T
df_BEA.drop(["Scrap, used and secondhand goods","Noncomparable imports and rest-of-the-world adjustment"],
            axis=1, inplace=True)
df_BEA.index=df_BEA.index.rename(None)

#Droping Construction and Wholesale trade sectors

df_BEA=df_BEA.drop(columns=["Construction", "Wholesale trade"], index=["Construction", "Wholesale trade"])

#Creating the Ratios of expenditures γ, Γ Matrix

ratios_expenditures=np.zeros((df_BEA.index.get_loc("Total Intermediate"),df_BEA.columns.get_loc("Total Intermediate")))
for col in range (df_BEA.columns.get_loc("Total Intermediate")):
    for row in range (df_BEA.index.get_loc("Total Intermediate")):
        if col==row:
            ratios_expenditures[row,col]= (df_BEA.iloc[row,col]/
                                           df_BEA.iloc[df_BEA.index.get_loc("Total use of products"),col])
        if col<row:
            ratios_expenditures[row,col]=(df_BEA.iloc[row,col]/
                                          df_BEA.iloc[df_BEA.index.get_loc("Total use of products"),col])
        if col>row:
            ratios_expenditures[row,col]=(df_BEA.iloc[row,col]/
                                          df_BEA.iloc[df_BEA.index.get_loc("Total use of products"),col])
df_ratios_expenditures=(
    pd.DataFrame(ratios_expenditures, columns= (df_BEA.columns[:df_BEA.columns.get_loc("Total Intermediate")])))
df_ratios_expenditures=(
    df_ratios_expenditures.
    apply(lambda x: round(x, 4)).set_index(df_BEA.index[:df_BEA.index.get_loc("Total Intermediate")]))

#Calculating Leontief Matrix L

Leontief= (np.identity(df_ratios_expenditures.to_numpy().shape[0])-df_ratios_expenditures.to_numpy())
df_Leontief=(
    pd.DataFrame(np.linalg.inv(Leontief),index=df_ratios_expenditures.index, columns=df_ratios_expenditures.columns))

#Calculating the average indirects conectivity in Leontief

average_Leontief=np.zeros(df_Leontief.shape)
for col in range (df_Leontief.shape[1]):
    for row in range (df_Leontief.shape[0]):
        if col==row:
            average_Leontief[row,col]= None
        if col<row:
            average_Leontief[row,col]= (df_Leontief.iloc[row,col]+df_Leontief.iloc[col,row])/2
        if col>row:
            average_Leontief[row,col]=None

df_average_Leontief= pd.DataFrame(average_Leontief, columns= df_Leontief.columns)
df_average_Leontief= df_average_Leontief.apply(lambda x: round(x, 4)).set_index(df_Leontief.index)


#Calibrations:



#Calibrating Ω as a matrix of ω_ji
Ω=(np.zeros((df_BEA.index.get_loc("Total Intermediate"),
            df_BEA.columns.get_loc("Total Intermediate"))))
for col in range (df_BEA.columns.get_loc("Total Intermediate")):
    for row in range (df_BEA.index.get_loc("Total Intermediate")):
        if col==row:
            Ω[row,col]=(df_BEA.iloc[row,col]/
                        df_BEA.iloc[df_BEA.index.get_loc("Total Intermediate"),col])
        if col<row:
            Ω[row,col]=(df_BEA.iloc[row,col]/
                        df_BEA.iloc[df_BEA.index.get_loc("Total Intermediate"),col])
        if col>row:
            Ω[row,col]=(df_BEA.iloc[row,col]/
                        df_BEA.iloc[df_BEA.index.get_loc("Total Intermediate"),col])

#Calibrating β_j 
β_j=np.zeros((df_BEA.index.get_loc("Total Intermediate"),1))
for i in range (df_BEA.columns.get_loc("Total Intermediate")):
    β_j[i,0]= (df_BEA.iloc[df_BEA.index.get_loc("Personal consumption expenditures"), i]/
                 df_BEA.iloc[df_BEA.index.get_loc("Personal consumption expenditures"),
                             df_BEA.columns.get_loc("Total Intermediate")])
#Calibrating a_j
a_j=np.zeros((df_BEA.index.get_loc("Total Intermediate"),1))
for i in range (df_BEA.columns.get_loc("Total Intermediate")):
    a_j[i,0]= (df_BEA.iloc[i,df_BEA.columns.get_loc("Compensation of employees")]/
                 df_BEA.iloc[i, df_BEA.columns.get_loc("Total industry output (basic prices)")])
    
#Calibrating ϵ_Q
ϵ_Q= 2.52 
    
#calibrating z_j

z_j=np.ones((df_BEA.index.get_loc("Total Intermediate"),1))

#Calibrating Consumption basket PcC

PcC= df_BEA.loc["Personal consumption expenditures", "Total Intermediate"]
    
# Calibrating Exports: C*_N+1

cstar= np.zeros((13,1))
cstar[1]=1

print(df_Leontief[["Mining"]].nlargest(n=5, columns=["Mining"]).to_markdown()) #Top 5 buyers of Mining

print((df_Leontief.loc["Mining"].nlargest(n=5)).to_markdown()) #Top 5 suppliers of Mining

|                                                      |   Mining |
|:-----------------------------------------------------|---------:|
| Mining                                               | 1.08969  |
| Manufacturing                                        | 0.870326 |
| Utilities                                            | 0.18927  |
| Government                                           | 0.103382 |
| Finance, insurance, real estate, rental, and leasing | 0.038598 |
| Commodities/Industries                               |     Mining |
|:-----------------------------------------------------|-----------:|
| Mining                                               | 1.08969    |
| Utilities                                            | 0.0133406  |
| Finance, insurance, real estate, rental, and leasing | 0.0118063  |
| Professional and business services                   | 0.00912485 |
| Manufacturing                                        | 0.00665345 |


### 3.2

In [3]:
#Building a solver so we can solve all the system of equations.


def solver(χ, downstream, shocks):
    
    if χ==0:
        
        χ_ji= np.ones((13,13)) + np.zeros((13,13))
        
    elif χ==1:
        
        if downstream==1:
        
            χ_ji=np.zeros((13,13))

            χ_ji[df_Leontief.index.get_loc("Manufacturing"),df_Leontief.columns.get_loc("Mining")]=1
            χ_ji[df_Leontief.index.get_loc("Utilities"),df_Leontief.columns.get_loc("Mining")]=1
            χ_ji[df_Leontief.index.get_loc("Government"),df_Leontief.columns.get_loc("Mining")]=1
            χ_ji[df_Leontief.index.get_loc("Mining"),df_Leontief.columns.get_loc("Mining")]=1
            χ_ji[df_Leontief.index.get_loc("Finance, insurance, real estate, rental, and leasing"),
                 df_Leontief.columns.get_loc("Mining")]=1

            χ_ji= np.ones((13,13))+χ_ji
            
        elif downstream==0:
            
            χ_ji=np.zeros((13,13))

            χ_ji[df_Leontief.index.get_loc("Mining"), df_Leontief.columns.get_loc("Manufacturing")]=1
            χ_ji[df_Leontief.index.get_loc("Mining"),df_Leontief.columns.get_loc("Utilities"),]=1
            χ_ji[df_Leontief.index.get_loc("Mining"),df_Leontief.columns.get_loc("Finance, insurance, real estate, rental, and leasing")]=1
            χ_ji[df_Leontief.index.get_loc("Mining"),df_Leontief.columns.get_loc("Mining")]=1
            χ_ji[df_Leontief.index.get_loc("Mining"),df_Leontief.columns.get_loc("Professional and business services") ]=1

            χ_ji= np.ones((13,13))+χ_ji
            
    shock=np.ones((13,1))
    shock[1]= shocks
    
    #Prices: 
    
    A= np.identity(13) - (1 - a_j) * z_j**(1-ϵ_Q) * Ω * χ_ji
    
    B= z_j**(1-ϵ_Q) * a_j
    
    P_j= np.linalg.solve(A, B)**(1/(1-ϵ_Q)) * shock

    #Q
    
    A= np.ones((13,1)) - ((1-a_j)**ϵ_Q * z_j**(ϵ_Q-1) * P_j**ϵ_Q * (Ω) * χ_ji**(-ϵ_Q)) @ (P_j**(-ϵ_Q))
    
    B= β_j * PcC / P_j + cstar

    Q_j= B/A
    
    #Consumption:
    
    C_j= β_j / (a_j * z_j**(ϵ_Q-1) * (np.transpose(P_j**(ϵ_Q-1)) @ (P_j * Q_j / PcC)))
    
    #House income:

    house_income=  np.sum(C_j * P_j / β_j)
    
    #exports:

    exports= np.sum(cstar*P_j)

    #Domestic GDP:

    GDP= house_income + exports

    #Aggregate Consumption

    Aggregate_Consumption= np.sum(β_j*np.log(C_j, where=C_j>0))
    
    results= [P_j, C_j, Q_j, house_income, GDP, Aggregate_Consumption]
    
    for i in range (len(results)-1):
        
        results[i] = np.round(results[i], 3)
    
    
    return results

#Solving without distortions χ_ji=0 and shocks=1

no_shock_no_distortions= solver(0, 0, 1)

## 3.3

In [4]:
#solving without distorsions and with shock:

shock_no_distortions= solver(0,0, 2)

difference= []

for i in range(6):
    
    difference.append((shock_no_distortions[i]-no_shock_no_distortions[i]))

difference

[array([[0.   ],
        [2.391],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ]]),
 array([[0.059],
        [0.   ],
        [0.074],
        [0.727],
        [0.   ],
        [0.026],
        [0.086],
        [0.718],
        [0.022],
        [0.167],
        [0.111],
        [0.059],
        [0.007]]),
 array([[-5.94767780e+04],
        [-6.27726000e+02],
        [-1.56498030e+04],
        [-1.05624885e+05],
        [-2.00000000e-03],
        [-7.83600000e+00],
        [-5.53600000e+01],
        [ 0.00000000e+00],
        [-6.00700000e+00],
        [-1.16870000e+01],
        [-1.76990000e+02],
        [-1.01060000e+01],
        [-5.18420000e+01]]),
 63.78299999999999,
 66.174,
 0.2771734922551561]

## 3.4

In [5]:
# solving with downstream distorsions and no shocks

no_shock_downstream=solver(1, 1, 1)

# solving with downstream distorsions and shocks

shock_downstream=solver(1, 1, 2)

differencedown= []

for i in range(6):
    
    differencedown.append((shock_downstream[i]-no_shock_downstream[i]))

differencedown

[array([[0.   ],
        [2.248],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ]]),
 array([[0.001],
        [0.   ],
        [0.002],
        [0.016],
        [0.   ],
        [0.   ],
        [0.002],
        [0.016],
        [0.001],
        [0.004],
        [0.002],
        [0.001],
        [0.   ]]),
 array([[-5.9614550e+03],
        [-6.5316000e+02],
        [-1.8901400e+03],
        [-1.6072689e+04],
        [-2.0000000e-03],
        [-9.3600000e+00],
        [-6.6964000e+01],
        [ 0.0000000e+00],
        [-7.0260000e+00],
        [-1.3627000e+01],
        [-2.1322500e+02],
        [-1.1996000e+01],
        [-1.0372000e+01]]),
 9.480999999999995,
 11.730000000000004,
 0.013760593765148377]

In [6]:
# solving with upstream distorsions and no shocks

no_shock_upstream= solver(1, 0, 1)

# solving with upstream distorsions and shocks

shock_downstream= solver(1, 0, 2)

differenceup= []

for i in range(6):
    
    differenceup.append((shock_downstream[i]-no_shock_upstream[i]))

differenceup

[array([[0.   ],
        [2.064],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ],
        [0.   ]]),
 array([[0.018],
        [0.   ],
        [0.022],
        [0.217],
        [0.   ],
        [0.008],
        [0.026],
        [0.215],
        [0.007],
        [0.05 ],
        [0.033],
        [0.018],
        [0.002]]),
 array([[-3.97696370e+04],
        [-1.14488000e+02],
        [-2.24888600e+04],
        [-1.45318046e+05],
        [-3.00000000e-03],
        [-1.13950000e+01],
        [-8.07040000e+01],
        [ 0.00000000e+00],
        [-8.69800000e+00],
        [-1.69140000e+01],
        [-2.57760000e+02],
        [-1.46800000e+01],
        [-7.48460000e+01]]),
 23.341000000000008,
 25.406000000000006,
 0.13278236125375514]

In [7]:
difference= []

for i in range(6):
    
    difference.append((differenceup[i]-differencedown[i]))

difference

[array([[ 0.   ],
        [-0.184],
        [ 0.   ],
        [ 0.   ],
        [ 0.   ],
        [ 0.   ],
        [ 0.   ],
        [ 0.   ],
        [ 0.   ],
        [ 0.   ],
        [ 0.   ],
        [ 0.   ],
        [ 0.   ]]),
 array([[0.017],
        [0.   ],
        [0.02 ],
        [0.201],
        [0.   ],
        [0.008],
        [0.024],
        [0.199],
        [0.006],
        [0.046],
        [0.031],
        [0.017],
        [0.002]]),
 array([[-3.38081820e+04],
        [ 5.38672000e+02],
        [-2.05987200e+04],
        [-1.29245357e+05],
        [-1.00000000e-03],
        [-2.03500000e+00],
        [-1.37400000e+01],
        [ 0.00000000e+00],
        [-1.67200000e+00],
        [-3.28700000e+00],
        [-4.45350000e+01],
        [-2.68400000e+00],
        [-6.44740000e+01]]),
 13.860000000000014,
 13.676000000000002,
 0.11902176748860677]